export const MapDatabase = [
  {
    "Level": "ระดับ 2: จอมยุทธ์ (Lv 10–19)",
    "Map_ID": "MAP-007",
    "ชื่อแมพ": "เทือกเขาหัวซาน (Mount Huashan — แมพปลดล็อกแรกของระดับ 2)",
    "โอกาสได้รับสกิล": "ขาว: 10% (Normal), เขียว: 8% (Elite), ฟ้า: 2% (Mini-Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 10% (Normal), เขียว: 30% (Normal), ฟ้า: 35% (Elite), ม่วง: 20% (Elite), ทอง: 5% (Elite), แดง: 0%",
    "ร้านค้า": "General Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ ม่วง–ทอง, Skill Scroll ระดับ เขียว–ฟ้า, Gold 960–1,440",
    "แมพถัดไปที่ปลดล็อก": ["MAP-010", "MAP-011"],
    "เงื่อนไขปลดล็อก": "ชนะ Mini-Boss ของ MAP-008"
  },
  {
    "Level": "ระดับ 6: เซียนยุทธ์ (Lv 50–59)",
    "Map_ID": "MAP-031",
    "ชื่อแมพ": "ดินแดนเสียงสวรรค์ (Celestial Sound Realm) — แมพปลดล็อกแรกของระดับ 6",
    "โอกาสได้รับสกิล": "ขาว: 0% (Normal), เขียว: 0% (Elite), ฟ้า: 3% (Elite), ม่วง: 8% (Mini-Boss), ทอง: 3% (Area Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 0% (Normal), เขียว: 0% (Normal), ฟ้า: 0% (Normal), ม่วง: 5% (Normal), ทอง: 30% (Normal), แดง: 40% (Elite)",
    "ร้านค้า": "General Shop, Elite Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Area Boss": "อุปกรณ์ระดับ ทอง–แดง, Skill Scroll ระดับ ม่วง–ทอง, Gold 10,200–25,500, Follower Recruitment Token",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ ม่วง–ทอง, Skill Scroll ระดับ ฟ้า–ม่วง, Gold 2,750–4,400",
    "แมพถัดไปที่ปลดล็อก": ["MAP-033", "MAP-034"],
    "เงื่อนไขปลดล็อก": "Player Level >= 50 และชนะ Area Boss ของ MAP-030"
  },
  {
    "Level_Header": "## ระดับเทพเจ้า",
    "Level_Info": "10: จักรพรรดิแห่งสวรรค์ (Lv 90)",
    "Map_ID": "MAP-050",
    "ชื่อแมพ": "ประตูสวรรค์ (Heaven's Gate) — แมพปลดล็อกแรกของระดับ 10",
    "โอกาสได้รับสกิล": "ขาว: 0% (Normal), เขียว: 0% (Elite), ฟ้า: 5% (Elite), ม่วง: 8% (Mini-Boss), ทอง: 3% (Area Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 0% (Normal), เขียว: 0% (Normal), ฟ้า: 0% (Normal), ม่วง: 5% (Normal), ทอง: 30% (Normal), แดง: 40% (Elite)",
    "ร้านค้า": "General Shop, Elite Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Area Boss": "อุปกรณ์ระดับ แดง (แน่นอน 3 ชิ้น), Skill Scroll ระดับ แดง (แน่นอน), Gold 25,500–63,750, Follower Recruitment Token",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ แดง (แน่นอน), Skill Scroll ระดับ แดง (แน่นอน), Gold 5,100–8,160",
    "รางวัลเคลียร์ Hidden Boss": "อุปกรณ์ระดับ แดง (แน่นอน 5 ชิ้น), Skill Scroll ระดับ แดง (แน่นอน 2 ชิ้น), Gold 55,000–137,500",
    "แมพถัดไปที่ปลดล็อก": ["MAP-052"],
    "เงื่อนไขปลดล็อก": "Player Level >= 90 และชนะ Area Boss ของ MAP-049"
  },
  {
    "Level": "ระดับ 7: เทพยุทธ์ (Lv 60–69)",
    "Map_ID": "MAP-036",
    "ชื่อแมพ": "วังเทพมาร (Divine Demon Palace) — แมพปลดล็อกแรกของระดับ 7",
    "โอกาสได้รับสกิล": "ขาว: 0% (Normal), เขียว: 0% (Elite), ฟ้า: 5% (Elite), ม่วง: 8% (Mini-Boss), ทอง: 3% (Area Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 0% (Normal), เขียว: 0% (Normal), ฟ้า: 0% (Normal), ม่วง: 5% (Normal), ทอง: 30% (Normal), แดง: 40% (Elite)",
    "ร้านค้า": "General Shop, Elite Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Area Boss": "อุปกรณ์ระดับ ทอง–แดง, Skill Scroll ระดับ ทอง–แดง, Gold 13,000–32,500, Follower Recruitment Token",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ ทอง–แดง, Skill Scroll ระดับ ม่วง–ทอง, Gold 3,350–5,360",
    "รางวัลเคลียร์ Hidden Boss": "อุปกรณ์ระดับ แดง (แน่นอน), Skill Scroll ระดับ แดง (50%), Gold 22,500–56,250",
    "แมพถัดไปที่ปลดล็อก": ["MAP-042"],
    "เงื่อนไขปลดล็อก": "Player Level >= 60 และชนะ Area Boss ของ MAP-035"
  },
  {
    "Level": "ระดับ 4: ปรมาจารย์ (Lv 30–39)",
    "Map_ID": "MAP-019",
    "ชื่อแมพ": "เกาะดอกท้อ (Peach Blossom Island) — แมพปลดล็อกแรกของระดับ 4",
    "โอกาสได้รับสกิล": "ขาว: 0% (Normal), เขียว: 5% (Elite), ฟ้า: 8% (Elite), ม่วง: 3% (Mini-Boss), ทอง: 1% (Area Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 0% (Normal), เขียว: 0% (Normal), ฟ้า: 5% (Normal), ม่วง: 30% (Normal), ทอง: 40% (Elite), แดง: 15% (Area Boss)",
    "ร้านค้า": "General Shop, Elite Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Area Boss": "อุปกรณ์ระดับ ทอง–แดง, Skill Scroll ระดับ ม่วง–ทอง, Gold 6,200–15,500, Follower Recruitment Token",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ ม่วง–ทอง, Skill Scroll ระดับ ฟ้า–ม่วง, Gold 1,900–3,040",
    "แมพถัดไปที่ปลดล็อก": ["MAP-021", "MAP-022"],
    "เงื่อนไขปลดล็อก": "Player Level >= 30 และชนะ Area Boss ของ MAP-018"
  },
  {
    "Level_Header": "## ระดับตำนาน",
    "Level_Info": "8: จักรพรรดิยุทธ์ (Lv 70–79)",
    "Map_ID": "MAP-042",
    "ชื่อแมพ": "สวรรค์ชั้นเก้า (Ninth Heaven) — แมพปลดล็อกแรกของระดับ 8",
    "โอกาสได้รับสกิล": "ขาว: 0% (Normal), เขียว: 0% (Elite), ฟ้า: 5% (Elite), ม่วง: 8% (Mini-Boss), ทอง: 3% (Area Boss)",
    "โอกาสได้รับอุปกรณ์": "ขาว: 0% (Normal), เขียว: 0% (Normal), ฟ้า: 0% (Normal), ม่วง: 5% (Normal), ทอง: 30% (Normal), แดง: 40% (Elite)",
    "ร้านค้า": "General Shop, Elite Shop",
    "AP ต่อครั้งสำรวจ": 1,
    "อัตราสำรวจ": "ศัตรูปกติ 55%, Elite 10%, Event 25%, Treasure 10%",
    "รางวัลเคลียร์ Area Boss": "อุปกรณ์ระดับ แดง (แน่นอน 2 ชิ้น), Skill Scroll ระดับ แดง, Gold 18,800–47,000, Follower Recruitment Token",
    "รางวัลเคลียร์ Mini-Boss": "อุปกรณ์ระดับ แดง (แน่นอน), Skill Scroll ระดับ ทอง–แดง, Gold 4,200–6,720",
    "รางวัลเคลียร์ Hidden Boss": "อุปกรณ์ระดับ แดง (แน่นอน 3 ชิ้น), Skill Scroll ระดับ แดง (แน่นอน), Gold 32,000–80,000",
    "แมพถัดไปที่ปลดล็อก": ["MAP-044", "MAP-045"],
    "เงื่อนไขปลดล็อก": "Player Level >= 70 และชนะ Area Boss ของ MAP-041"
  }
];
